Repository MorseKOB/PyKOB, pull requests merged in 2021-01, with the labels that each got.

#216 Add text value to 'record' and record the decoded text
  kobmain.py
  pykob/recorder.py
Labels: enhancement

#217 Add KOB Server URL config option to allow using an alternate server.
  Configure.py
  pykob/config.py
  pykob/internet.py
Labels: enhancement

#221 Update call to pykob.morse to use new parameters.
  Feed.py
Labels: bug

#224 Lk 191 handle nonstandard code sequences
  kobactions.py
  kobmain.py
  pykob/__init__.py
  pykob/kob.py
  pykob/morse.py
Labels: enhancement

#222 Add ability for Feed.py to feed from a PyKOB recording (json) file.
  Feed.py
  pykob/recorder.py
Labels: enhancement

#225 Es 223 config
  Configure.py
  Weather.py
  kobconfig.py
  kobmain.py
  kobwindow.py
  pykob/config.py
Labels: Common Config, Common module (pykob code), enhancement

#252 Pwd #249 create tabbed preferences with separate advanced tab
  pykob/preferencesWindow.py
Labels: Common Config, Common module (pykob code), MKOB

#254 Fix problem in master branch with un-tabbed references to preferenceswindow sections resulting in nearly empty preferences windows.
  pykob/preferencesWindow.py
Labels: bug
